### ISSUE TITLE
How do use queryByAccount?

### ISSUE THREAD

**Issue by ksemba** [KILTprotocol/sdk-js#715]
Hi everyone,

I'm new to KILT and was going through the Quick Start guide to get familiar with the basic concepts. I created my own DID and stored it on the KILT bockchain (I used the new Checkout Service to pay with PayPal for that transaction - very handy!). 

Then I wanted to modify the quick start example where you query by account name for 'john_doe' to use my new, personal DID (I modified the actual DID - not sure it is safe to publically post it):

```
// const encodedJohnDoeDetails = await api.call.did.queryByWeb3Name('john_doe')
const encodedJohnDoeDetails = await api.call.did.queryByAccount('did:kilt:mypersonalDID')
```

But this throws an error:

```
/home/kurt/kilt-test/node_modules/@polkadot/types-create/cjs/create/type.js:67
    firstError = new Error(`createType(${type}):: ${error.message}`);
                 ^
Error: createType(DidApiAccountId):: Decoding did:kilt:mypersonalDID: Invalid base58 character ":" (0x3a) at index 3
    at createTypeUnsafe (/home/kurt/kilt-test/node_modules/@polkadot/types-create/cjs/create/type.js:67:18)
    at TypeRegistry.createTypeUnsafe (/home/kurt/kilt-test/node_modules/@polkadot/types/cjs/create/registry.js:295:46)
    at /home/kurt/kilt-test/node_modules/@polkadot/api/cjs/base/Decorate.js:503:103
    at Array.map (<anonymous>)
    at /home/kurt/kilt-test/node_modules/@polkadot/api/cjs/base/Decorate.js:503:80
    at /home/kurt/kilt-test/node_modules/@polkadot/api/cjs/promise/decorateMethod.js:56:26
    at new Promise (<anonymous>)
    at decorateCall (/home/kurt/kilt-test/node_modules/@polkadot/api/cjs/promise/decorateMethod.js:51:10)
    at Object.queryByAccount (/home/kurt/kilt-test/node_modules/@polkadot/api/cjs/promise/decorateMethod.js:87:73)
    at /home/kurt/kilt-test/quickstart_kurt.ts:14:54
```

I assume the problem is that I'm providing my DID and not my "account name"? If so, where do I find my account name? I cannot use a web3name as this requires some $KILT to pay for and I don't have an account with Kraken nor Gate.io so I'd have to go through all kinds of trouble to get tokens onto my Sporran wallet. 

Thanks!

**Comment by rflechtner** [comment]
Hi and welcome!

If you are using our sdk, there is an easier way to look up information related to your DID, which is the `resolve` function (check out [this example in our docs](https://docs.kilt.io/docs/develop/sdk/cookbook/dids/did-query)). If you want to take the more low-level, bare-bones approach and use the polkadot-js api directly, you'd need to call `query` instead of `queryByAccount` and drop the `kilt:did:` part of the DID, like so:
```
api.call.did.query('mypersonalDID')
```
`queryByAccount` instead makes use of the feature that [you can link a token-holding account to your DID](https://docs.kilt.io/docs/develop/sdk/cookbook/account_linking/account-link), so it looks whether a DID is linked to the queried account and returns it.

BTW if you are using typescript in your project, and/or if your code editor supports it, you should be able to see short annotations on the different `api.call.did.*` methods explaining what they do.

**Comment by rflechtner** [comment]
Only you have control over your DID document, so adding a new service endpoints entry is a manual process. You can do so for example via Sporran's "Manage on-chain DID" tab. Making edits to your on-chain DID document does however require KILTs.
You should check out support.kilt.io, there's a ton of tips and instructions for how to use Sporran and other applications. It also has an article on [how to publish and link to your credentials](https://support.kilt.io/support/solutions/articles/80001014863-how-do-i-make-my-credentials-public). There's also a [Discord](https://discord.gg/hX4pc8rdHS) and a [Telegram](https://t.me/KILTProtocolChat) where you can ask questions and find support.

> By the way: I don't really "authenticate" my DID, right? The only thing I can do here is to validate that it exists on chain and that it is still active? So if someone knows my DID, then he/she could easily assume my identity? There is no way to prove that this specific DID belongs to me?

When you created your DID, you used a cryptographic key to sign your request. This key is now linked in your DID document. Because only you have the corresponding private key, you can prove by producing signatures that you are the rightful owner of this DID. Such a signature is for example required to change the document or deactivate your DID.

**Comment by ksemba** [comment]
Thank you @rflechtner - this is super helpful. As your support goes beyond the initial issue I raised, I will close the issue and will join your Discord community.
